import { writeFile } from "node:fs/promises";

import { FIXTURES } from "../src/lib/fixtures/manifest.ts";

/**
 * Writes `docs/FIXTURES.md` from the manifest.
 *
 * Generated rather than hand-written so the documentation cannot drift from the
 * pages it describes. A fixture whose expectations change updates the manifest,
 * the tests and this document together.
 *
 *     pnpm docs:fixtures
 */

const header = `# Test fixtures

<!-- Generated by \`pnpm docs:fixtures\` from src/lib/fixtures/manifest.ts. -->

Nine pages, each isolating one keyboard behaviour, with the expected outcome
written down. They exist so a change to the agent can be judged against
something whose answer is already known — "it found three issues" is not a
result unless you know how many were there.

Browse them at \`/fixtures\` while the app is running.

## Determinism

The expectations below only hold because the pages are built to be boring:

- **A fixture page contains only the controls its case needs.** No navigation,
  no "back to index" link, nothing focusable from a shared layout. One stray
  anchor and every expected order here is wrong.
- **No timers, no animation, no network.** Behaviour is driven by focus events
  only, so the same traversal produces the same trace.
- **Run against a production build.** \`next dev\` renders a focusable
  \`<nextjs-portal>\` overlay that joins the tab order, so the e2e config starts
  \`next build && next start\`. Worth knowing when auditing your own app too.

## Running the tests

\`\`\`bash
# The fixtures behave as documented. No AI involved.
pnpm test:e2e tests/e2e/fixtures.spec.ts

# The agent against them, with a mocked provider. No network, no cost.
pnpm test:e2e tests/e2e/fixtures-agent.spec.ts

# Against a real provider. Opt-in, costs money, not deterministic.
RUN_REAL_AI_TESTS=1 pnpm test:e2e tests/e2e/fixtures-real-ai.spec.ts
\`\`\`

`;

const body = FIXTURES.map((fixture) => {
  const issues =
    fixture.expectation.reportableIssues.length === 0
      ? "**None.** A run that reports anything here has produced a false positive."
      : fixture.expectation.reportableIssues.map((issue) => `- \`${issue}\``).join("\n");

  const focusOrder =
    fixture.expectedFocusOrder.length === 0
      ? "_Nothing is focusable._"
      : fixture.expectedFocusOrder
          .map((label, index) => `${index + 1}. ${label}`)
          .join("\n");

  const unreachable =
    fixture.expectedUnreachable.length === 0
      ? "_None._"
      : fixture.expectedUnreachable.map((label) => `- ${label}`).join("\n");

  return `## \`${fixture.path}\` — ${fixture.title}

${fixture.summary}

**Initial focus:** ${fixture.initialFocus ?? "_none; focus starts on the document_"}

**Expected focus order**

${focusOrder}

**Discovered but unreachable**

${unreachable}

**Expected browser behavior**

${fixture.expectation.browserBehavior}

**Expected AI behavior**

${fixture.expectation.aiBehavior}

**Expected evidence**

${fixture.expectation.evidence}

**Expected reportable issues**

${issues}
`;
}).join("\n---\n\n");

await writeFile("docs/FIXTURES.md", `${header}---\n\n${body}`, "utf8");
process.stdout.write("Wrote docs/FIXTURES.md\n");
